version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
  model:
    build:
      context: .
      dockerfile: backend/model_api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
